site_name: Xeondb Documentation
site_url: https://voyrox.github.io/Xeondb/
site_description: XeonDB is the cloud database for data intensive apps that require predictable performance and low latency.

theme:
  name: mkdocs
  locale: en
  custom_dir: overrides
  color_mode: dark
  nav_style: dark
  user_color_mode_toggle: false
nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Query Examples: query-examples.md
  - Drivers: drivers.md
  - Permissions: permissions.md
  - Deployment: deployment.md

extra_css:
  - css/theme.css

extra_javascript:
  - js/remove.js
