network:
  host: 0.0.0.0
  port: 9876

storage:
  dataDir: /var/lib/blazedb/data

limits:
  maxLineBytes: 1048576
  maxConnections: 1024

wal:
  walFsync: periodic
  walFsyncIntervalMs: 50
  walFsyncBytes: 1048576

memtable:
  memtableMaxBytes: 33554432

sstable:
  sstableIndexStride: 16
